services:
  - type: web
    name: velora-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://velora-one-rouge.vercel.app
      - key: BACKEND_URL
        value: https://by-jessika-backend.onrender.com
